# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CloudSkills Python application

on:
  push:
    branches:
      - '*'
  create:
    branches:
      - '*'
      
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f Application/requirements.txt ]; then pip install -r Application/requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics      
    - name: Test folder creation
      run: |
        # mkdir testresults
        # pwd
        # ls Tests/unit_tests
        pytest Test/unit_tests --junitxml=./testresults/test-results.xml
          
    - name: Unity Test Publisher
      uses: rainbow-duck-games/unity-test-publisher@v0.2.4
      with:
        testFolder: Tests/unit_tests
        # PyTest library version.
        # args: --junitxml 
        # File name where the results will be generated. File is XML
        reportPaths: ./testresults/test-results.xml        
